### ISSUE TITLE
deserialization error

### ISSUE THREAD

**Issue by ladnane** [Dessia-tech/dessia_common#244]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

opening a workflow run raise an exception (that end up killing a spawned worker !): 
https://platform-testing.dessia.tech/objects/dessia_common.workflow.core.WorkflowRun/62733fbb78114351f108c3c1

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

```
[deadlock-detector] a process holding a robust mutex died. recovering...
309055 /var/www/platform-packages/pymongo/topology.py:164: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
309056   warnings.warn(
309057 /usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py:229: Warning: specific to_dict of class Point3D should implement use_pointers, memo and path arguments
309058   warnings.warn(f'specific to_dict of class {class_.__name__} '
309059 /usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py:229: Warning: specific to_dict of class Vector3D should implement use_pointers, memo and path arguments
309060   warnings.warn(f'specific to_dict of class {class_.__name__} '
309061 /usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py:229: Warning: specific to_dict of class PlaneFace3D should implement use_pointers, memo and path arguments
309062   warnings.warn(f'specific to_dict of class {class_.__name__} '
309063 --- Logging error ---
309064 Traceback (most recent call last):
309065   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 224, in dict_to_object
309066     obj = class_.dict_to_object(dict_,
309067 TypeError: dict_to_object() got an unexpected keyword argument 'path'
309068
309069 During handling of the above exception, another exception occurred:
309070
309071 Traceback (most recent call last):
309072   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 776, in _instantiate_python_object_from_dict
309073     python_object = self.python_class.dict_to_object(self.object_dict)
309074   File "/usr/local/lib/python3.9/dist-packages/dessia_common/workflow/core.py", line 1388, in dict_to_object
309075     pointers_memo.update(dereference_jsonpointers(dict_))
309076   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 485, in dereference_jsonpointers
309077     pointers_memo[ref] = deserialize(serialized_element=serialized_element,
309078   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 160, in deserialize
309079     return dict_to_object(serialized_element, global_dict=global_dict,
309080   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 231, in dict_to_object
309081     obj = class_.dict_to_object(dict_)
309082   File "/usr/local/lib/python3.9/dist-packages/volmdlr/faces.py", line 3995, in dict_to_object
309083     plane3d = Plane3D.dict_to_object(dict_['surface3d'],
309084   File "/usr/local/lib/python3.9/dist-packages/dessia_common/core.py", line 247, in dict_to_object
309085     obj = dict_to_object(dict_=dict_, class_=cls,
309086   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 210, in dict_to_object
309087     pointers_memo.update(dereference_jsonpointers(dict_))
309088   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 484, in dereference_jsonpointers
309089     serialized_element = get_in_object_from_path(dict_, ref)
309090   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 69, in get_in_object_from_path
309091     element = get_in_object_from_path(object_, element['$ref'])
309092   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 69, in get_in_object_from_path
309093     element = get_in_object_from_path(object_, element['$ref'])
309094   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 69, in get_in_object_from_path
309095     element = get_in_object_from_path(object_, element['$ref'])
309096   [Previous line repeated 972 more times]
309097   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 63, in get_in_object_from_path
309098     segments = path.lstrip('#/').split('/')
309099 RecursionError: maximum recursion depth exceeded while calling a Python object
309100
309101 During handling of the above exception, another exception occurred:
309102
309103 Traceback (most recent call last):
309104   File "/var/www/platform-packages/flask/app.py", line 2447, in wsgi_app
309105     response = self.full_dispatch_request()
309106   File "/var/www/platform-packages/flask/app.py", line 1952, in full_dispatch_request
309107     rv = self.handle_user_exception(e)
309108   File "/var/www/platform-packages/flask_cors/extension.py", line 165, in wrapped_function
309109     return cors_after_request(app.make_response(f(*args, **kwargs)))
309110   File "/var/www/platform-packages/flask/app.py", line 1821, in handle_user_exception
309111     reraise(exc_type, exc_value, tb)
309112   File "/var/www/platform-packages/flask/_compat.py", line 39, in reraise
309113     raise value
309114   File "/var/www/platform-packages/flask/app.py", line 1950, in full_dispatch_request
309115     rv = self.dispatch_request()
309116   File "/var/www/platform-packages/flask/app.py", line 1936, in dispatch_request
309117     return self.view_functions[rule.endpoint](**req.view_args)
309118   File "/var/www/platform-packages/dessia_platform_backend/routes/__init__.py", line 112, in active_user_function
309119     return function(*args, **kwargs)
309120   File "/var/www/platform-packages/flask_limiter/extension.py", line 705, in __inner
309121     return obj(*a, **k)
309122   File "<string>", line 2, in get_object
309123   File "/var/www/platform-packages/pony/orm/core.py", line 519, in new_func
309124     result = func(*args, **kwargs)
309125   File "/var/www/platform-packages/dessia_platform_backend/routes/objects.py", line 468, in get_object
309126     json_value = obj.to_json(
309127   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 707, in to_json
309128     dict_['export_formats'] = self.export_formats()
309129   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 663, in export_formats
309130     elif hasattr(self.python_object, '_export_formats'):
309131   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 595, in python_object
309132     self._python_object = self._instantiate_python_object_from_dict()
309133   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 786, in _instantiate_python_object_from_dict
309134     raise backend_exceptions.DeserializationError(msg, track)
309135 Traceback (most recent call last):
309136   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 224, in dict_to_object
309137     obj = class_.dict_to_object(dict_,
309138 TypeError: dict_to_object() got an unexpected keyword argument 'path'
309139
309140 During handling of the above exception, another exception occurred:
309141
309142 Traceback (most recent call last):
309143   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 776, in _instantiate_python_object_from_dict
309144     python_object = self.python_class.dict_to_object(self.object_dict)
309145   File "/usr/local/lib/python3.9/dist-packages/dessia_common/workflow/core.py", line 1388, in dict_to_object
309146     pointers_memo.update(dereference_jsonpointers(dict_))
309147   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 485, in dereference_jsonpointers
309148     pointers_memo[ref] = deserialize(serialized_element=serialized_element,
309149   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 160, in deserialize
309150     return dict_to_object(serialized_element, global_dict=global_dict,
309151   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 231, in dict_to_object
309152     obj = class_.dict_to_object(dict_)
309153   File "/usr/local/lib/python3.9/dist-packages/volmdlr/faces.py", line 3995, in dict_to_object
309154     plane3d = Plane3D.dict_to_object(dict_['surface3d'],
309155   File "/usr/local/lib/python3.9/dist-packages/dessia_common/core.py", line 247, in dict_to_object
309156     obj = dict_to_object(dict_=dict_, class_=cls,
309157   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 210, in dict_to_object
309158     pointers_memo.update(dereference_jsonpointers(dict_))
309159   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 484, in dereference_jsonpointers
309160     serialized_element = get_in_object_from_path(dict_, ref)
309161   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 69, in get_in_object_from_path
309162     element = get_in_object_from_path(object_, element['$ref'])
309163   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 69, in get_in_object_from_path
309164     element = get_in_object_from_path(object_, element['$ref'])
309165   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 69, in get_in_object_from_path
309166     element = get_in_object_from_path(object_, element['$ref'])
309167   [Previous line repeated 972 more times]
309168   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 63, in get_in_object_from_path
309169     segments = path.lstrip('#/').split('/')
309170 RecursionError: maximum recursion depth exceeded while calling a Python object
309171
309172 During handling of the above exception, another exception occurred:
309173
309174 Traceback (most recent call last):
309175   File "/var/www/platform-packages/flask/app.py", line 2447, in wsgi_app
309176     response = self.full_dispatch_request()
309177   File "/var/www/platform-packages/flask/app.py", line 1952, in full_dispatch_request
309178     rv = self.handle_user_exception(e)
309179   File "/var/www/platform-packages/flask_cors/extension.py", line 165, in wrapped_function
309180     return cors_after_request(app.make_response(f(*args, **kwargs)))
309181   File "/var/www/platform-packages/flask/app.py", line 1821, in handle_user_exception
309182     reraise(exc_type, exc_value, tb)
309183   File "/var/www/platform-packages/flask/_compat.py", line 39, in reraise
309184     raise value
309185   File "/var/www/platform-packages/flask/app.py", line 1950, in full_dispatch_request
309186     rv = self.dispatch_request()
309187   File "/var/www/platform-packages/flask/app.py", line 1936, in dispatch_request
309188     return self.view_functions[rule.endpoint](**req.view_args)
309189   File "/var/www/platform-packages/dessia_platform_backend/routes/__init__.py", line 112, in active_user_function
309190     return function(*args, **kwargs)
309191   File "/var/www/platform-packages/flask_limiter/extension.py", line 705, in __inner
309192     return obj(*a, **k)
309193   File "<string>", line 2, in get_object
309194   File "/var/www/platform-packages/pony/orm/core.py", line 519, in new_func
309195     result = func(*args, **kwargs)
309196   File "/var/www/platform-packages/dessia_platform_backend/routes/objects.py", line 468, in get_object
309197     json_value = obj.to_json(
309198   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 707, in to_json
309199     dict_['export_formats'] = self.export_formats()
309200   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 663, in export_formats
309201     elif hasattr(self.python_object, '_export_formats'):
309202   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 595, in python_object
309203     self._python_object = self._instantiate_python_object_from_dict()
309204   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 786, in _instantiate_python_object_from_dict
309205     raise backend_exceptions.DeserializationError(msg, track)
309206 dessia_platform_backend.exceptions.DeserializationError: 
309207
309208 During handling of the above exception, another exception occurred:
309209
309210 Traceback (most recent call last):
309211   File "/usr/lib/python3.9/logging/__init__.py", line 1082, in emit
309212     stream.write(msg + self.terminator)
309213 UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 13906: ordinal not in range(128)
309214
309215 During handling of the above exception, another exception occurred:
309216
309217 Traceback (most recent call last):
309218   File "/var/www/platform-packages/flask/app.py", line 2464, in __call__
309219     return self.wsgi_app(environ, start_response)
309220   File "/var/www/platform-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
309221     return self.app(environ, start_response)
309222   File "/var/www/platform-packages/flask/app.py", line 2450, in wsgi_app
309223     response = self.handle_exception(e)
309224   File "/var/www/platform-packages/flask_cors/extension.py", line 165, in wrapped_function
309225     return cors_after_request(app.make_response(f(*args, **kwargs)))
309226   File "/var/www/platform-packages/flask/app.py", line 1871, in handle_exception
309227     self.log_exception((exc_type, exc_value, tb))
309228   File "/var/www/platform-packages/flask/app.py", line 1891, in log_exception
309229     self.logger.error(
309230   File "/usr/lib/python3.9/logging/__init__.py", line 1471, in error
309231     self._log(ERROR, msg, args, **kwargs)
309232   File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
309233     self.handle(record)
309234   File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
309235     self.callHandlers(record)
309236   File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
309237     hdlr.handle(record)
309238   File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
309239     self.emit(record)
309240   File "/usr/lib/python3.9/logging/__init__.py", line 1087, in emit
309241     self.handleError(record)
309242   File "/usr/lib/python3.9/logging/__init__.py", line 1001, in handleError
309243     traceback.print_exception(t, v, tb, None, sys.stderr)
309244   File "/usr/lib/python3.9/traceback.py", line 105, in print_exception
309245     print(line, file=file, end="")
309246 UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 8801: ordinal not in range(128)
309247 ... monitored exception detected, respawning worker 1 (pid: 21600)...
309248 Respawned uWSGI worker 1 (new pid: 21605)
309249 [deadlock-detector] a process holding a robust mutex died. recovering...


```

* **Possible fixes**

* **Please tell us about your environment:**
  - platform : testing
  - branch: testing
  - commit:  ac76a41a7c623482f2d20688921f73eeb2cc9bfd (latest)
  - python version:

**Comment by MackJoly** [comment]
How many time do you think it will take ?

**Comment by MackJoly** [comment]
I deleted the workflowrun object, i shared steps to do in platform-testing > workspace PipingLayout to reproduce it, the wf takes 30 second to run

**Comment by masfaraud** [comment]
Not a dessia common problem, backend
