### ISSUE TITLE
Recursive error on breakdown

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/dessia_common#272]
```
749086	--- Logging error ---
749087	Traceback (most recent call last):
749088	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 224, in dict_to_object
749089	    obj = class_.dict_to_object(dict_,
749090	TypeError: dict_to_object() got an unexpected keyword argument 'path'
749091	
749092	During handling of the above exception, another exception occurred:
749093	
749094	Traceback (most recent call last):
749095	  File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 832, in _instantiate_python_object_from_dict
749096	    python_object = self.python_class.dict_to_object(self.object_dict)
749097	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/workflow/core.py", line 1434, in dict_to_object
749098	    pointers_memo.update(dereference_jsonpointers(dict_))
749099	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 488, in dereference_jsonpointers
749100	    pointers_memo[ref] = deserialize(serialized_element=serialized_element,
749101	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 160, in deserialize
749102	    return dict_to_object(serialized_element, global_dict=global_dict,
749103	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 231, in dict_to_object
749104	    obj = class_.dict_to_object(dict_)
749105	  File "/usr/local/lib/python3.9/dist-packages/volmdlr/faces.py", line 3998, in dict_to_object
749106	    surface2d = Surface2D.dict_to_object(dict_['surface2d'],
749107	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/core.py", line 246, in dict_to_object
749108	    obj = dict_to_object(dict_=dict_, class_=cls,
749109	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 210, in dict_to_object
749110	    pointers_memo.update(dereference_jsonpointers(dict_))
749111	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 487, in dereference_jsonpointers
749112	    serialized_element = get_in_object_from_path(dict_, ref)
749113	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 85, in get_in_object_from_path
749114	    element = get_in_object_from_path(object_, element['$ref'])
749115	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 85, in get_in_object_from_path
749116	    element = get_in_object_from_path(object_, element['$ref'])
749117	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 85, in get_in_object_from_path
749118	    element = get_in_object_from_path(object_, element['$ref'])
749119	  [Previous line repeated 975 more times]
749120	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 79, in get_in_object_from_path
749121	    segments = path.lstrip('#/').split('/')
749122	RecursionError: maximum recursion depth exceeded while calling a Python object
749123	
749124	During handling of the above exception, another exception occurred:
749125	
749126	Traceback (most recent call last):
749127	  File "/var/www/platform-packages/flask/app.py", line 2447, in wsgi_app
749128	    response = self.full_dispatch_request()
749129	  File "/var/www/platform-packages/flask/app.py", line 1952, in full_dispatch_request
749130	    rv = self.handle_user_exception(e)
749131	  File "/var/www/platform-packages/flask_cors/extension.py", line 165, in wrapped_function
749132	    return cors_after_request(app.make_response(f(*args, **kwargs)))
749133	  File "/var/www/platform-packages/flask/app.py", line 1821, in handle_user_exception
749134	    reraise(exc_type, exc_value, tb)
749135	  File "/var/www/platform-packages/flask/_compat.py", line 39, in reraise
749136	    raise value
749137	  File "/var/www/platform-packages/flask/app.py", line 1950, in full_dispatch_request
749138	    rv = self.dispatch_request()
749139	  File "/var/www/platform-packages/flask/app.py", line 1936, in dispatch_request
749140	    return self.view_functions[rule.endpoint](**req.view_args)
749141	  File "/var/www/platform-packages/dessia_platform_backend/routes/__init__.py", line 112, in active_user_function
749142	    return function(*args, **kwargs)
749143	  File "/var/www/platform-packages/flask_limiter/extension.py", line 705, in __inner
749144	    return obj(*a, **k)
749145	  File "/var/www/platform-packages/dessia_platform_backend/routes/objects.py", line 359, in object_display_settings
749146	    return jsonify([ds.to_dict() for ds in obj.display_settings()])
749147	  File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 733, in display_settings
749148	    elif hasattr(self.python_object, 'display_settings'):
749149	  File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 648, in python_object
749150	    self._python_object = self._instantiate_python_object_from_dict()
749151	  File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 843, in _instantiate_python_object_from_dict
749152	    raise backend_exceptions.DeserializationError(msg, track)
749153	/var/www/platform-packages/retricon/retricon.py:251: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
749154	  out_img = im.resize((width, width), Image.ANTIALIAS)
749155	/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py:229: Warning: specific to_dict of class PlaneFace3D should implement use_pointers, memo and path arguments
749156	  warnings.warn(f'specific to_dict of class {class_.__name__} '
749157	/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py:229: Warning: specific to_dict of class Point3D should implement use_pointers, memo and path arguments
749158	  warnings.warn(f'specific to_dict of class {class_.__name__} '
749159	/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py:229: Warning: specific to_dict of class Vector3D should implement use_pointers, memo and path arguments
749160	  warnings.warn(f'specific to_dict of class {class_.__name__} '
749161	--- Logging error ---
749162	Traceback (most recent call last):
749163	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 224, in dict_to_object
749164	    obj = class_.dict_to_object(dict_,
749165	TypeError: dict_to_object() got an unexpected keyword argument 'path'
749166	
749167	During handling of the above exception, another exception occurred:
749168	
749169	Traceback (most recent call last):
749170	  File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 832, in _instantiate_python_object_from_dict
749171	    python_object = self.python_class.dict_to_object(self.object_dict)
749172	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/workflow/core.py", line 1434, in dict_to_object
749173	    pointers_memo.update(dereference_jsonpointers(dict_))
749174	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 488, in dereference_jsonpointers
749175	    pointers_memo[ref] = deserialize(serialized_element=serialized_element,
749176	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 160, in deserialize
749177	    return dict_to_object(serialized_element, global_dict=global_dict,
749178	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 231, in dict_to_object
749179	    obj = class_.dict_to_object(dict_)
749180	  File "/usr/local/lib/python3.9/dist-packages/volmdlr/faces.py", line 3998, in dict_to_object
749181	    surface2d = Surface2D.dict_to_object(dict_['surface2d'],
749182	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/core.py", line 246, in dict_to_object
749183	    obj = dict_to_object(dict_=dict_, class_=cls,
749184	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 210, in dict_to_object
749185	    pointers_memo.update(dereference_jsonpointers(dict_))
749186	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 487, in dereference_jsonpointers
749187	    serialized_element = get_in_object_from_path(dict_, ref)
749188	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 85, in get_in_object_from_path
749189	    element = get_in_object_from_path(object_, element['$ref'])
749190	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 85, in get_in_object_from_path
749191	    element = get_in_object_from_path(object_, element['$ref'])
749192	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 85, in get_in_object_from_path
749193	    element = get_in_object_from_path(object_, element['$ref'])
749194	  [Previous line repeated 975 more times]
749195	  File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 79, in get_in_object_from_path
749196	    segments = path.lstrip('#/').split('/')
749197	RecursionError: maximum recursion depth exceeded while calling a Python object
749198	
749199	During handling of the above exception, another exception occurred:
749200	
749201	Traceback (most recent call last):
749202	  File "/var/www/platform-packages/flask/app.py", line 2447, in wsgi_app
749203	    response = self.full_dispatch_request()
749204	  File "/var/www/platform-packages/flask/app.py", line 1952, in full_dispatch_request
749205	    rv = self.handle_user_exception(e)
749206	  File "/var/www/platform-packages/flask_cors/extension.py", line 165, in wrapped_function
749207	    return cors_after_request(app.make_response(f(*args, **kwargs)))
749208	  File "/var/www/platform-packages/flask/app.py", line 1821, in handle_user_exception
749209	    reraise(exc_type, exc_value, tb)
749210	  File "/var/www/platform-packages/flask/_compat.py", line 39, in reraise
749211	    raise value
749212	  File "/var/www/platform-packages/flask/app.py", line 1950, in full_dispatch_request
749213	    rv = self.dispatch_request()
749214	  File "/var/www/platform-packages/flask/app.py", line 1936, in dispatch_request
749215	    return self.view_functions[rule.endpoint](**req.view_args)
749216	  File "/var/www/platform-packages/dessia_platform_backend/routes/__init__.py", line 112, in active_user_function
749217	    return function(*args, **kwargs)
749218	  File "/var/www/platform-packages/flask_limiter/extension.py", line 705, in __inner
749219	    return obj(*a, **k)
749220	  File "/var/www/platform-packages/dessia_platform_backend/routes/objects.py", line 359, in object_display_settings
749221	    return jsonify([ds.to_dict() for ds in obj.display_settings()])
749222	  File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 733, in display_settings
749223	    elif hasattr(self.python_object, 'display_settings'):
749224	  File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 648, in python_object
749225	    self._python_object = self._instantiate_python_object_from_dict()
749226	  File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 843, in _instantiate_python_object_from_dict
749227	    raise backend_exceptions.DeserializationError(msg, track)
```

**Comment by masfaraud** [comment]
solved?

**Comment by GhislainJ** [comment]
I think this has been solved by now ?

**Comment by masfaraud** [comment]
Done a while ago
