### ISSUE TITLE
get models does not work with latest master

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/dessia_common#291]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
On testing.dessia.ovh (front = master latest, back = master latest), by changing dessia_common on latest master, get models does not work

Here is log:

28 [2022-07-07 19:31:47,641: ERROR/ForkPoolWorker-1] Task dessia_platform_backend.tasks.tasks.insert_object_from_dict[c75633e9-f27a-4aa9-849f-96264c97a599] raised unexpected: NameError("name 'dc' is not defined")
2129 Traceback (most recent call last):
2130   File "/var/www/platform-packages/celery/app/trace.py", line 450, in trace_task
2131     R = retval = fun(*args, **kwargs)
2132   File "/var/www/platform-packages/celery/app/trace.py", line 731, in __protected_call__
2133     return self.run(*args, **kwargs)
2134   File "/var/www/platform-packages/dessia_platform_backend/tasks/tasks.py", line 165, in insert_object_from_dict
2135     memo, stats = deo.insert_db()
2136   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1280, in insert_db
2137     python_object = self.python_object
2138   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 647, in python_object
2139     self._python_object = self._instantiate_python_object_from_dict()
2140   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 852, in _instantiate_python_object_from_dict
2141     self.metadata_db_update()
2142   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1392, in metadata_db_update
2143     data = getattr(self, data_name)
2144   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 657, in size
2145     self._size = len(bson.BSON.encode(dc.stringify_dict_keys(self.object_dict)))
2146 NameError: name 'dc' is not defined
2147 [2022-07-07 19:31:48,024: ERROR/ForkPoolWorker-1] Task dessia_platform_backend.tasks.tasks.insert_object_from_dict[46231e65-e56e-4b14-b889-d50ade0c312b] raised unexpected: NameError("name 'dc' is not defined")
2148 Traceback (most recent call last):
2149   File "/var/www/platform-packages/celery/app/trace.py", line 450, in trace_task
2150     R = retval = fun(*args, **kwargs)
2151   File "/var/www/platform-packages/celery/app/trace.py", line 731, in __protected_call__
2152     return self.run(*args, **kwargs)
2153   File "/var/www/platform-packages/dessia_platform_backend/tasks/tasks.py", line 165, in insert_object_from_dict
2154     memo, stats = deo.insert_db()
2155   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1280, in insert_db
2156     python_object = self.python_object
2157   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 647, in python_object
2158     self._python_object = self._instantiate_python_object_from_dict()
2159   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 852, in _instantiate_python_object_from_dict
2160     self.metadata_db_update()
2161   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1392, in metadata_db_update
2162     data = getattr(self, data_name)
2163   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 657, in size
2164     self._size = len(bson.BSON.encode(dc.stringify_dict_keys(self.object_dict)))
2165 NameError: name 'dc' is not defined
2166 [2022-07-07 19:31:48,032: ERROR/ForkPoolWorker-1] Task dessia_platform_backend.tasks.tasks.insert_object_from_dict[797e5751-429b-4da9-a473-79475dddea30] raised unexpected: NameError("name 'dc' is not defined")
2167 Traceback (most recent call last):
2168   File "/var/www/platform-packages/celery/app/trace.py", line 450, in trace_task
2169     R = retval = fun(*args, **kwargs)
2170   File "/var/www/platform-packages/celery/app/trace.py", line 731, in __protected_call__
2171     return self.run(*args, **kwargs)
2172   File "/var/www/platform-packages/dessia_platform_backend/tasks/tasks.py", line 165, in insert_object_from_dict
2173     memo, stats = deo.insert_db()
2174   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1280, in insert_db
2175     python_object = self.python_object
2176   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 647, in python_object
2177     self._python_object = self._instantiate_python_object_from_dict()
2178   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 852, in _instantiate_python_object_from_dict
2179     self.metadata_db_update()
2180   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1392, in metadata_db_update
2181     data = getattr(self, data_name)
2182   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 657, in size
2183     self._size = len(bson.BSON.encode(dc.stringify_dict_keys(self.object_dict)))
2184 NameError: name 'dc' is not defined
2185 [2022-07-07 19:31:50,052: INFO/MainProcess] Task dessia_platform_backend.tasks.tasks.insert_object_from_dict[40e58d75-1122-45f6-89a0-fbe744cc4424] received
2186 [2022-07-07 19:31:51,590: ERROR/ForkPoolWorker-1] Task dessia_platform_backend.tasks.tasks.insert_object_from_dict[40e58d75-1122-45f6-89a0-fbe744cc4424] raised unexpected: NameError("name 'dc' is not defined")
2187 Traceback (most recent call last):
2188   File "/var/www/platform-packages/celery/app/trace.py", line 450, in trace_task
2189     R = retval = fun(*args, **kwargs)
2190   File "/var/www/platform-packages/celery/app/trace.py", line 731, in __protected_call__
2191     return self.run(*args, **kwargs)
2192   File "/var/www/platform-packages/dessia_platform_backend/tasks/tasks.py", line 165, in insert_object_from_dict
2193     memo, stats = deo.insert_db()
2194   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1280, in insert_db
2195     python_object = self.python_object
2196   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 647, in python_object
2197     self._python_object = self._instantiate_python_object_from_dict()
2198   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 852, in _instantiate_python_object_from_dict
2199     self.metadata_db_update()
2200   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1392, in metadata_db_update
2201     data = getattr(self, data_name)
2202   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 657, in size
2203     self._size = len(bson.BSON.encode(dc.stringify_dict_keys(self.object_dict)))
2204 NameError: name 'dc' is not defined

* **Please tell us about your environment:**
  
  - branch: master
  - commit:  latest
  - python version:

**Comment by MackJoly** [comment]
I have this log too : 
[2022-07-08 00:00:08,831: ERROR/ForkPoolWorker-1] Task dessia_platform_backend.tasks.tasks.insert_models_and_workflows[8cb8caa4-1eeb-427b-b4f8-54ccfd613517] raised unexpected: TypeError("to_dict() missing 1 required positional argument: 'self'")
2331 Traceback (most recent call last):
2332   File "/var/www/platform-packages/celery/app/trace.py", line 450, in trace_task
2333     R = retval = fun(*args, **kwargs)
2334   File "/var/www/platform-packages/celery/app/trace.py", line 731, in __protected_call__
2335     return self.run(*args, **kwargs)
2336   File "/var/www/platform-packages/dessia_platform_backend/tasks/tasks.py", line 257, in insert_models_and_workflows
2337     insert_object_from_dict.apply_async((model.to_dict(), 'dessia', True),
2338   File "/usr/local/lib/python3.9/dist-packages/dessia_common/workflow/core.py", line 561, in to_dict
2339     ser_value, memo = serialize_with_pointers(value, memo=memo,
2340   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 88, in serialize_with_pointers
2341     serialized = value.to_dict()
2342 TypeError: to_dict() missing 1 required positional argument: 'self'

**Comment by MackJoly** [comment]
I thing this is no more an actual topic
