### ISSUE TITLE
dessia_common.breakdown.ExtractionError:

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/dessia_common#325]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
Error with stl file reading

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages
On renault.dessia.ovh -- Please change package renault_custom to readstlfiles branch

![image](https://user-images.githubusercontent.com/61141035/183531132-67a471d1-b8e9-4f1e-b8ac-fee746c07d27.png)

![image](https://user-images.githubusercontent.com/61141035/183531071-61fbd86d-b9ad-4596-bef1-d2e9d7369dc8.png)

```
[2022-08-08 23:15:18,695: WARNING/ForkPoolWorker-6] Object of class renault_custom.core.ReadSTLFiles got an extraction error: Cannot get segment 3 from path #/values/3 in element {<dessia_common.workflow.core.TypedVariable object at 0x7fe95e2fcb50>: [<renault_custom.components.Geometry object at 0x7fe95e363430>], <dessia_common.workflow.core.TypedVariableWithDefaultValue object at 0x7fe95e2fcb80>: '', <dessia_common.workflow.core.TypedVariableWithDefaultValue object at 0x7fe95e2a2be0>: None, <dessia_common.workflow.core.TypedVariable object at 0x7fe92964df40>: <renault_custom.core.ReadSTLFiles object at 0x7fe95e240ee0>, <dessia_common.workflow.core.TypedVariable object a
913 [2022-08-08 23:15:18,695: WARNING/ForkPoolWorker-6] Falling back to dict_to_object
914 [2022-08-08 23:15:18,741: ERROR/ForkPoolWorker-6] Task dessia_platform_backend.tasks.tasks.object_method[7a4cf1dd-6b68-4334-b079-4fe85b79c968] raised unexpected: ExtractionError("Cannot get segment input_values from path #/input_values/0/0 in element {'name': '', 'object_class': 'renault_custom.core.ReadSTLFiles', 'package_version': '0.0.3.dev167', 'log': None, 'components': [{'$ref': '#/input_values/0/0'}]}")
915 Traceback (most recent call last):
916   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 92, in get_in_object_from_path
917     element = extract_from_object(element, segment)
918   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 59, in extract_from_object
919     raise ExtractionError(f'Cannot extract segment {segment} from object {str(object_)[:200]}')
920 dessia_common.breakdown.ExtractionError: Cannot extract segment 3 from object {<dessia_common.workflow.core.TypedVariable object at 0x7fe95e2fcb50>: [<renault_custom.components.Geometry object at 0x7fe95e363430>], <dessia_common.workflow.core.TypedVariableWithDefaultValue objec
921
922 The above exception was the direct cause of the following exception:
923
924 Traceback (most recent call last):
925   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1232, in reference_dict
926     corresponding_object = dc_bd.get_in_object_from_path(global_object, path)
927   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 95, in get_in_object_from_path
928     raise ExtractionError(err_msg) from err
929 dessia_common.breakdown.ExtractionError: Cannot get segment 3 from path #/values/3 in element {<dessia_common.workflow.core.TypedVariable object at 0x7fe95e2fcb50>: [<renault_custom.components.Geometry object at 0x7fe95e363430>], <dessia_common.workflow.core.TypedVariableWithDefaultValue object at 0x7fe95e2fcb80>: '', <dessia_common.workflow.core.TypedVariableWithDefaultValue object at 0x7fe95e2a2be0>: None, <dessia_common.workflow.core.TypedVariable object at 0x7fe92964df40>: <renault_custom.core.ReadSTLFiles object at 0x7fe95e240ee0>, <dessia_common.workflow.core.TypedVariable object a
930
931 During handling of the above exception, another exception occurred:
932
933 Traceback (most recent call last):
934   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 92, in get_in_object_from_path
935     element = extract_from_object(element, segment)
936   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 73, in extract_from_object
937     raise ExtractionError(message_error)
938 dessia_common.breakdown.ExtractionError: Cannot extract segment input_values from object {'name': '', 'object_class': 'renault_custom.core.ReadSTLFiles', 'package_version': '0.0.3.dev167', 'log': None, 'components': [{'$ref': '#/input_values/0/0'}]}
939
940 The above exception was the direct cause of the following exception:
941
942 Traceback (most recent call last):
943   File "/var/www/platform-packages/celery/app/trace.py", line 450, in trace_task
944     R = retval = fun(*args, **kwargs)
945   File "/var/www/platform-packages/celery/app/trace.py", line 731, in __protected_call__
946     return self.run(*args, **kwargs)
947   File "/var/www/platform-packages/dessia_platform_backend/tasks/tasks.py", line 225, in object_method
948     deo_result.insert_db()
949   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1373, in insert_db
950     referenced_obj_dict, descendants, memo, stats2 = self.reference_python_object(self.python_object,
951   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1289, in reference_python_object
952     dict_attr, descs_attr, memo, stats_attr = self.choose_reference(attribute_value, global_object=obj,
953   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1201, in choose_reference
954     return self.reference_dict(value, global_object=global_object, path=path, memo=memo)
955   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1247, in reference_dict
956     value_dict, descs, memo, stats_value = self.choose_reference(value, global_object=global_object,
957   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1201, in choose_reference
958     return self.reference_dict(value, global_object=global_object, path=path, memo=memo)
959   File "/var/www/platform-packages/dessia_platform_backend/models/engineering.py", line 1236, in reference_dict
960     corresponding_object = class_.python_class.dict_to_object(dict_)
961   File "/usr/local/lib/python3.9/dist-packages/dessia_common/core.py", line 242, in dict_to_object
962     obj = dict_to_object(dict_=dict_, class_=cls, force_generic=force_generic, global_dict=global_dict,
963   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 203, in dict_to_object
964     global_dict, pointers_memo = update_pointers_data(global_dict=global_dict, current_dict=dict_,
965   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 449, in update_pointers_data
966     pointers_memo.update(dereference_jsonpointers(current_dict))
967   File "/usr/local/lib/python3.9/dist-packages/dessia_common/utils/serialization.py", line 489, in dereference_jsonpointers
968     serialized_element = get_in_object_from_path(dict_, ref)
969   File "/usr/local/lib/python3.9/dist-packages/dessia_common/breakdown.py", line 95, in get_in_object_from_path
970     raise ExtractionError(err_msg) from err
971 dessia_common.breakdown.ExtractionError: Cannot get segment input_values from path #/input_values/0/0 in element {'name': '', 'object_class': 'renault_custom.core.ReadSTLFiles', 'package_version': '0.0.3.dev167', 'log': None, 'components': [{'$ref': '#/input_values/0/0'}]}
```
Feel free to contact me !

**Comment by MackJoly** [comment]
Step to debug : 
- Test on another version of dessia_common (Is it related to the version ?)
- Test to empty the database (not a solution because if a customer has a lot of data and needs to delete them, it's not great)

**Comment by GhislainJ** [comment]
Hi @MackJoly , thanks for the report. We encountered a lot of these lately and some have been fixed only on dev branch. Did you try to make it work with it ?

**Comment by MackJoly** [comment]
Hi Ghislain, by using frontend dev, backend dev and dessia common dev, it works ! I think the branch used on the backend wasn't up to date. Thank you for your help !
