### ISSUE TITLE
check_platform -  Object is not equal to itself after serialization/deserialization with references

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/dessia_common#385]
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**

volumemode._check_platform() with references

vol0.primitives[0]._check_platform()
data diff:  ([], [], ['#/faces/0/alpha', '#/faces/1/alpha', '#/faces/2/alpha', '#/faces/3/alpha', '#/faces/4/alpha', '#/faces/5/alpha', '#/faces/6/alpha', '#/faces/7/alpha', '#/faces/8/alpha', '#/faces/9/alpha', '#/faces/10/alpha', ...
'#/faces/2441/alpha', '#/faces/2442/alpha', '#/faces/2443/alpha', '#/faces/2444/alpha', '#/faces/2445/alpha', '#/faces/2446/alpha'])
Traceback (most recent call last):
  File "C:\Users\Mack\AppData\Local\Programs\Python\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\Mack\Documents\git\dessia_common\dessia_common\core.py", line 610, in _check_platform
    raise dessia_common.errors.DeserializationError('Object is not equal to itself'
dessia_common.errors.DeserializationError: Object is not equal to itself after serialization/deserialization

When I go deeper, 

vol0.primitives[0].faces[0]._check_platform()
data diff:  ([], [], ['#/alpha']) with the same error

I can't give you any usecase because when I save in file it works..

* **Please tell us about your environment:**
  
  - branch: master
  - commit:  
  - python version: 3.10

**Comment by MackJoly** [comment]
The problem come from volmdlr, wrong deposite
